config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'

  get '/rider_signup', to: 'riders#new'
  post '/rider_signup', to: 'riders#create'
  get '/driver_signup', to: 'drivers#new'
  post '/driver_signup', to: 'drivers#create'

  get    '/rider_login',   to: 'sessions#rider_new'
  post   '/rider_login',   to: 'sessions#rider_create'
  delete '/rider_logout',  to: 'sessions#rider_destroy'
  get    '/driver_login',   to: 'sessions#driver_new'
  post   '/driver_login',   to: 'sessions#driver_create'
  delete '/driver_logout',  to: 'sessions#driver_destroy'

  resources :riders
  resources :drivers
  resources :routes
  resources :rides 
  resources :relationships
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if rider_logged_in?
  	  redirect_to current_rider
  	elsif driver_logged_in?
  	  redirect_to current_driver
  	end
  end

  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
  <body>
  <div class="center jumbotron">
    <h1>Help</h1>
    <p>
      Contact our support team for any queries.<br>
      <a href="mailto:prachurgupta10@gmail.com">Prachur Gupta</a><br>
      Phone: +91 8179893888
    </p>
  </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
  <div class="center jumbotron">
    <h1>Welcome to the P-Ride App</h1>
      <p>
          Welcome to the P-Ride App, A Ride Sharing Application!
      </p>
    <%= link_to "Rider - Sign up", rider_signup_path, class: "btn btn-lg btn-primary" %>
    <span style="margin:25px;"></span>
    <%= link_to "Driver - Sign Up", driver_signup_path, class: "btn btn-lg btn-primary" %>
  </div>