config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'

  get '/rider_signup', to: 'riders#new'
  post '/rider_signup', to: 'riders#create'
  get '/driver_signup', to: 'drivers#new'
  post '/driver_signup', to: 'drivers#create'

  get    '/rider_login',   to: 'sessions#rider_new'
  post   '/rider_login',   to: 'sessions#rider_create'
  delete '/rider_logout',  to: 'sessions#rider_destroy'
  get    '/driver_login',   to: 'sessions#driver_new'
  post   '/driver_login',   to: 'sessions#driver_create'
  delete '/driver_logout',  to: 'sessions#driver_destroy'

  resources :riders
  resources :drivers
  resources :routes
  resources :rides 
  resources :relationships
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Demo App
    by <a href="mailto:prachurgupta10@gmail.com">Prachur Gupta</a>.
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to 'p-ride', root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path, id:"try" %></li>
          <li><%= link_to "Help",   help_path, id:"try" %></li>
          <% if rider_logged_in? %>
            <li class="dropdown">
              <a id="" href="#" class="dropdown-toggle" data-toggle="dropdown">
                Menu <b class="caret"></b>
              </a> 
              <ul class="dropdown-menu">
                <li><%= link_to "Edit Profile", edit_rider_path(current_rider) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", rider_logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% elsif driver_logged_in? %> 
            <li class="dropdown" >
              <a id="try" href="#" class="dropdown-toggle" data-toggle="dropdown">
                Menu <b class="caret"></b>
              </a> 
              <ul class="dropdown-menu">
                <li><%= link_to "Edit Profile", edit_driver_path(current_driver) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", driver_logout_path, method: :delete %>
                </li>
              </ul>
            </li>           
          <% else %> 
            <li><%= link_to "Rider Login", rider_login_url, id:"try" %></li>
            <li><%= link_to "Driver Login", driver_login_url, id:"try" %></li>  
          <% end %>        
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

<%= javascript_tag do %>
  $('.dropdown-toggle').dropdown();
<% end %>